name: Call home

on: push

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPATCH_TEST_TOKEN }}
          repository: anttimaki/repo-dispatch-test-private
          event-type: repo2-push
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
